name: diffusion
channels:
  - simpleitk/label/dev
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
#  - _openmp_mutex
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - cudatoolkit
  - cycler=0.10.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
#  - libgcc-ng
#  - libgomp
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
#  - libstdcxx-ng
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - notebook=6.4.6
  - numexpr=2.7.3
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyzmq=22.2.1
  - qt=5.9.7
  - readline=8.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - simpleitk=2.1rc2
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - pip:
    - absl-py==0.15.0
    - accelerate==0.7.1
    - aiohttp==3.8.0
    - aiosignal==1.2.0
    - albumentations==1.1.0
    - antlr4-python3-runtime==4.8
    - antspyx==0.3.1
    - arrow==1.2.1
    - asgiref==3.5.0
    - astunparse==1.6.3
    - async-timeout==4.0.0
    - binaryornot==0.4.4
    - cachetools==4.2.4
    - catalyst==22.4
    - chardet==4.0.0
    - charset-normalizer==2.0.7
    - chart-studio==1.1.0
    - click==8.0.3
    - coco-froc-analysis==0.0.29
    - colorama==0.4.4
    - colorlog==6.6.0
    - commonmark==0.9.1
    - configparser==5.1.0
    - construct==2.10.68
    - contourpy==1.0.5
    - cookiecutter==1.7.3
    - cython==0.29.24
    - data==0.4
    - deprecated==1.2.13
    - distro==1.6.0
    - django==4.0.2
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - edafa==0.1.5
    - effdet==0.2.4
    - efficientnet-pytorch==0.7.1
    - einops==0.4.1
    - ema-pytorch==0.0.10
    - ensemble-boxes==1.0.7
    - et-xmlfile==1.1.0
    - evalutils==0.3.0
    - filelock==3.8.0
    - flatbuffers==2.0
    - frozenlist==1.2.0
    - fsspec==2021.11.0
    - funcsigs==1.0.2
    - future==0.18.2
    - gast==0.4.0
    - gevent==21.12.0
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grad-cam==1.3.7
    - greenlet==1.1.2
    - grpcio==1.41.1
    - h5py==3.6.0
    - huggingface-hub==0.10.0
    - humanize==3.14.0
    - hydra-colorlog==1.1.0
    - hydra-core==1.1.1
    - hydra-slayer==0.4.0
    - idna==3.3
    - imageio==2.10.3
    - install==1.3.4
    - itk==5.2.1.post1
    - itk-core==5.2.1.post1
    - itk-filtering==5.2.1.post1
    - itk-io==5.2.1.post1
    - itk-numerics==5.2.1.post1
    - itk-registration==5.2.1.post1
    - itk-segmentation==5.2.1.post1
    - jinja2-time==0.2.0
    - joblib==1.2.0
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kornia==0.6.7
    - latex==0.7.0
    - libauc==1.2.0
    - libclang==12.0.0
    - llvmlite==0.39.1
    - markdown==3.3.4
    - matplotlib==3.6.0
    - mlxtend==0.21.0
    - monai==0.7.0
    - multidict==5.2.0
    - names==0.3.0
    - networkx==2.6.3
    - nibabel==3.2.1
    - numba==0.56.4
    - numpy==1.22.4
    - oauthlib==3.1.1
    - odach==0.1.5-2107010420
    - omegaconf==2.1.1
    - opencv-python==4.5.4.60
    - opencv-python-headless==4.5.4.60
    - opencxr==1.2.0
    - openpyxl==3.0.9
    - openslide-python==1.2.0
    - opt-einsum==3.3.0
    - panimg==0.9.1
    - pathtools==0.1.2
    - patsy==0.5.2
    - pipreqs==0.4.11
    - plotly==5.4.0
    - poyo==0.5.0
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pydantic==1.10.2
    - pydeprecate==0.3.1
    - pydicom==2.2.2
    - pyelastix==1.2
    - pyerf==1.0.1
    - pylibjpeg==1.4.0
    - pylibjpeg-libjpeg==1.3.1
    - pylibjpeg-openjpeg==1.2.1
    - pylibjpeg-rle==1.3.0
    - pyparsing==2.4.7
    - pypng==0.0.21
    - python-dotenv==0.19.1
    - python-slugify==5.0.2
    - pytorch-ignite==0.4.7
    - pytorch-lightning==1.5.1
    - pytorch-ranger==0.1.1
    - pyvips==2.2.1
    - pywavelets==1.2.0
    - pyyaml==6.0
    - qudida==0.0.4
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rich==10.13.0
    - rsa==4.7.2
    - scikit-build==0.12.0
    - scikit-image==0.18.3
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - seaborn==0.11.2
    - sentry-sdk==1.4.3
    - setproctitle==1.2.3
    - shared-memory-dict==0.7.2
    - shortuuid==1.0.7
    - shutilwhich==1.1.0
    - smmap==5.0.0
    - sqlparse==0.4.2
    - statsmodels==0.13.2
    - subprocess32==3.5.4
    - tempdir==0.7.1
    - tenacity==8.0.1
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.5
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.22.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - thop==0.0.31-2005241907
    - threadpoolctl==3.0.0
    - tifffile==2021.11.2
    - timm==0.6.11
    - torch-optimizer==0.3.0
    - torch-tb-profiler==0.3.1
    - torchinfo==1.6.5
    - torchio==0.18.73
    - torchmetrics==0.8.0
    - torchsampler==0.1.1
    - torchxrayvision==0.0.32
    - tqdm==4.62.3
    - tsnecuda==0.1.1
    - ttach==0.0.3
    - typing-extensions==4.4.0
    - umap==0.1.1
    - urllib3==1.26.7
    - wandb==0.12.19
    - webcolors==1.11.1
    - werkzeug==2.0.2
    - wget==3.2
    - wrapt==1.13.3
    - yarg==0.1.9
    - yarl==1.7.2
    - yaspin==2.1.0
    - zope-event==4.5.0
    - zope-interface==5.4.0